name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Run Specific Job'
        type: boolean
        required: false
      custom_message:
        description: 'Enter a custom message'
        type: string
        required: true  


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    if: inputs.run_job == true
    runs-on: ubuntu-latest
    env:
      CUSTOM_MESSAGE: ${{ inputs.custom_message }}
    steps: 
      - name: 'Printing Custom Message'
        run: echo $CUSTOM_MESSAGE
      - name: 'Printing run-job boolean value'
        run: echo ${{ inputs.run_job }}
